// examples/nextjs/src/app/blog/[slug]/page.tsx
import Link from 'next/link';

import { stet } from '../../../lib/stet';

export default async function Post({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const post = await stet.posts.get(slug);

  return (
    <main>
      <p>
        <Link href="/blog">← Blog</Link>
      </p>
      <h1>{post.title}</h1>
      <p className="muted">Updated {new Date(post.updatedAt).toLocaleDateString('en-GB')}</p>
      {post.fields.cover == null ? null : <img src={post.fields.cover.url} alt="" />}
      {post.fields.body == null ? (
        <p className="muted">This post has no body yet.</p>
      ) : (
        <div dangerouslySetInnerHTML={{ __html: post.fields.body.html }} />
      )}
    </main>
  );
}

// examples/nuxt/app/pages/blog/[slug].vue
<script setup lang="ts">
const route = useRoute();
const { data: post } = await useFetch(() => `/api/posts/${String(route.params.slug)}`);
</script>

<template>
  <main v-if="post != null">
    <p><NuxtLink to="/blog">← Blog</NuxtLink></p>
    <h1>{{ post.title }}</h1>
    <p class="muted">Updated {{ new Date(post.updatedAt).toLocaleDateString('en-GB') }}</p>
    <img v-if="post.fields.cover != null" :src="post.fields.cover.url" :alt="post.title" />
    <p v-if="post.fields.body == null" class="muted">This post has no body yet.</p>
    <div v-else v-html="post.fields.body.html" />
  </main>
</template>
