// examples/nextjs/src/app/blog/page.tsx
import Link from 'next/link';

import { stet } from '../../lib/stet';

export default async function Blog() {
  const posts = await stet.posts.list();

  return (
    <main>
      <h1>Blog</h1>
      {posts.length === 0 ? <p className="muted">No posts yet. Write one in Stet.</p> : null}
      {posts.map((post) => (
        <article key={post.id}>
          <h2>
            <Link href={`/blog/${post.slug}`}>{post.title}</Link>
          </h2>
          {post.fields.summary == null ? null : <p>{post.fields.summary}</p>}
        </article>
      ))}
    </main>
  );
}

// examples/nuxt/app/pages/blog/index.vue
<script setup lang="ts">
const { data: posts } = await useFetch('/api/posts');
</script>

<template>
  <main>
    <h1>Blog</h1>
    <p v-if="posts != null && posts.length === 0" class="muted">No posts yet. Write one in Stet.</p>
    <article v-for="post in posts" :key="post.id">
      <h2>
        <NuxtLink :to="`/blog/${post.slug}`">{{ post.title }}</NuxtLink>
      </h2>
      <p v-if="post.fields.summary != null">{{ post.fields.summary }}</p>
    </article>
  </main>
</template>
