// examples/nuxt/app/pages/blog/index.vue
<script setup lang="ts">
const { data: posts } = await useFetch('/api/posts');
</script>

<template>
  <main>
    <h1>Blog</h1>
    <p v-if="posts != null && posts.length === 0" class="muted">No posts yet. Write one in Stet.</p>
    <article v-for="post in posts" :key="post.id">
      <h2>
        <NuxtLink :to="`/blog/${post.slug}`">{{ post.title }}</NuxtLink>
      </h2>
      <p v-if="post.fields.summary != null">{{ post.fields.summary }}</p>
    </article>
  </main>
</template>

// examples/sveltekit/src/routes/blog/+page.svelte
<script lang="ts">
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();
</script>

<main>
  <h1>Blog</h1>
  {#if data.posts.length === 0}
    <p class="muted">No posts yet. Write one in Stet.</p>
  {/if}
  {#each data.posts as post (post.id)}
    <article>
      <h2>
        <a href="/blog/{post.slug}">{post.title}</a>
      </h2>
      {#if post.fields.summary != null}
        <p>{post.fields.summary}</p>
      {/if}
    </article>
  {/each}
</main>
