// examples/sveltekit/src/routes/+page.svelte
<script lang="ts">
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();
</script>

<main>
  <h1>{data.landing.fields.headline ?? data.landing.title}</h1>
  {#if data.landing.fields.pitch != null}
    <!-- Safe to inject: Stet returns sanitised HTML for rich text fields. -->
    <div>{@html data.landing.fields.pitch.html}</div>
  {/if}
  <p>
    <a href="/blog">Read the blog →</a>
  </p>
  <p class="muted">
    This page renders the “Landing” map; the blog renders the “Posts” collection. Both are typed
    from the model built in the Stet UI.
  </p>
</main>

// examples/tanstack/src/routes/index.tsx
import { createFileRoute, Link } from '@tanstack/react-router';

import { fetchLanding } from '../content';

export const Route = createFileRoute('/')({
  loader: () => fetchLanding(),
  component: Home,
});

function Home() {
  const landing = Route.useLoaderData();

  return (
    <main>
      <h1>{landing.fields.headline ?? landing.title}</h1>
      {landing.fields.pitch == null ? null : (
        <div dangerouslySetInnerHTML={{ __html: landing.fields.pitch.html }} />
      )}
      <p>
        <Link to="/blog">Read the blog →</Link>
      </p>
      <p className="muted">
        This page renders the “Landing” map; the blog renders the “Posts” collection. Both are typed
        from the model built in the Stet UI.
      </p>
    </main>
  );
}
